# Linear regression
This project is the mimic version of Linear regression, implemented in the concise version with Pytorch api. 

In [1]:
import numpy as np
import torch
from torch.utils import data
from d2l import torch as d2l

Synthetic data is generated in this step.

In [3]:
true_w = torch.tensor([2,-3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w,true_b,100)

Build the 'data_iter'.

In [4]:
def load_array(data_arrays,batch_size, is_train=True):
    dataset = data.TensorDataset(*data_arrays)
    return data.DataLoader(dataset, batch_size, shuffle=is_train)


In [5]:
batch_size = 10
data_iter = load_array((features,labels), batch_size)


Now we define the model with torch.nn. 

In [10]:
from torch import nn
net = nn.Sequential(nn.Linear(2,1))

In [12]:
net[0].weight.data.normal_(0,0.01)
net[0].bias.data.fill_(0)

tensor([0.])

Learning criteria. 

In [13]:
loss = nn.MSELoss()

Training


In [14]:
trainer = torch.optim.SGD(net.parameters(),lr=0.03)

In [16]:
num_epochs = 3
for epoch in range(num_epochs):
    for X,y in data_iter:
        l = loss(net(X), y)
        trainer.zero_grad()
        l.backward()
        trainer.step()
    l = loss(net(features),labels)
    print(f'epoch {epoch + 1 }, loss {l:f}')

epoch 1, loss 0.207895
epoch 2, loss 0.059175
epoch 3, loss 0.016993


In [19]:
net[0].weight

Parameter containing:
tensor([[ 1.9390, -3.3531]], requires_grad=True)

In [18]:
net[0].bias.data

tensor([4.0936])